version: "3.9"
services:
  bookstore:
    image: bookstore:0.0.1-SNAPSHOT
    container_name: bookstore
    ports:
      - 8080:8080
    depends_on:
      - keycloak
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=http://keycloak:8888/realms/bookstore
      - DEBUG=true
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    container_name: keycloak
    ports:
      - 8888:8888
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=8888
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./bookstore-keycloak-realm.json:/opt/keycloak/data/import/bookstore-realm.json
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - 27017:27017
