version: "3.9"
services:
  bookstore:
    image: bookstore:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - DEBUG=true
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:6.0-ubi8
